# Generated by Django 4.2.2 on 2023-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_team_number_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_master',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
