# Generated by Django 4.2.2 on 2023-06-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_team_game_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('challenge_text', models.TextField()),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost_per_station', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='jail_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='jail_time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('CHASER', 'Chaser'), ('RUNNER', 'Runner')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='TransportDoneByTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stops', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeDoneByTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('catched_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
    ]
