# Generated by Django 4.2.2 on 2023-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_game_id_team_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttype',
            name='javascript_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
