# Generated by Django 4.2.2 on 2023-07-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_team_jail_time_alter_team_jail_time_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengedonebyteam',
            old_name='timestamp',
            new_name='timestamp_end',
        ),
        migrations.AddField(
            model_name='challengedonebyteam',
            name='open',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengedonebyteam',
            name='timestamp_start',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('RUNNER', 'Runner'), ('CHASER', 'Chaser')], max_length=20, null=True),
        ),
    ]
