# Generated by Django 4.2.2 on 2023-06-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameID',
            new_name='Game',
        ),
    ]
