# Generated by Django 4.2.2 on 2023-06-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_challenge_transporttype_team_jail_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='game_id',
            new_name='game',
        ),
    ]
