# Generated by Django 4.2.2 on 2023-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_team_money_team_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='jail_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='jail_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
